<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	 <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\startup.mp3" />
    <None Remove="Assets\startup.wav" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <EmbeddedResource Include="Assets\startup.wav" />
  </ItemGroup>

</Project>
